version: '3.7'
services:
  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image:  elasticsearch:7.12.0
    container_name: elasticsearch
    environment:
      - cluster.name=devops
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    container_name: kibana
    image: kibana:7.12.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  logstash:
    image: logstash:7.7.0
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
    #command: logstash -f /config-dir/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - 5009:5009
      - 5010:5010
      - 5011:5011
      - 9600:9600
      - 8089:8089
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

volumes:
  elasticsearch-data:
    driver: local

networks:
  default:
    external:
      name: packtpubdevop_nt